include $(THEOS)/makefiles/common.mk

TOOL_NAME = VCNStreamDaemon

VCNStreamDaemon_FILES = main.m
VCNStreamDaemon_CFLAGS = -fobjc-arc -O3
VCNStreamDaemon_FRAMEWORKS = Foundation

include $(THEOS_MAKE_PATH)/tool.mk
