include $(THEOS)/makefiles/common.mk

TWEAK_NAME = VCNextCamera

VCNextCamera_FILES = Tweak.x
VCNextCamera_CFLAGS = -fobjc-arc -O3
VCNextCamera_FRAMEWORKS = AVFoundation CoreMedia CoreVideo CoreImage VideoToolbox IOSurface Security

include $(THEOS_MAKE_PATH)/tweak.mk
