include $(THEOS)/makefiles/common.mk

APPLICATION_NAME = VCNext

VCNext_FILES = main.m AppDelegate.m RootViewController.m
VCNext_FRAMEWORKS = UIKit CoreGraphics PhotosUI AVFoundation
VCNext_CFLAGS = -fobjc-arc -O3

include $(THEOS_MAKE_PATH)/application.mk
