include $(THEOS)/makefiles/common.mk

TWEAK_NAME = VCNextOverlay

VCNextOverlay_FILES = Overlay.x
VCNextOverlay_CFLAGS = -fobjc-arc -O3
VCNextOverlay_FRAMEWORKS = UIKit CoreGraphics QuartzCore

include $(THEOS_MAKE_PATH)/tweak.mk
